trigger:
- main



stages:
- stage: Resources-Azure
  displayName: Resources Azure stage
  jobs:
  - job: Infra
    displayName: Infra
    pool:
      vmImage: 'ubuntu-latest'

    steps:


    - script: |
        az -v 
      displayName: 'az cli version'


