trigger:
- main

variables:
  rgName: 'hello-world-nodejs-rg'
  location: 'westeurope'
  resourceSuffix: '$RANDOM'
  webName: 'helloworld-nodejs-$(resourceSuffix)'
  planName: 'helloworld-nodejs-plan'

stages:
- stage: ResourcesAzure
  displayName: Resources Azure stage
  jobs:
  - job: Infra
    displayName: Infra
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'contoso-pierrc (cebd1df9-6ffd-4c75-aaac-3b76fe2c5fac)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create \
            --name $(rgName) \
            --location $(location)
          
          az appservice plan create \
            --name $(planName) \
            --resource-group $(rgName) \
            --sku B1 \
            --is-linux

          az webapp create \
            --name $(webName) \
            --resource-group $(rgName) \
            --plan $(planName) \
            --runtime "node|16-lts"
      displayName: 'App Service Deployment'
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'contoso-pierrc (cebd1df9-6ffd-4c75-aaac-3b76fe2c5fac)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          URL=$(az webapp list \
            --resource-group $(rgName) \
            --query "[].{hostName: defaultHostName, state: state}" \
            --output table)
          echo $URL
      displayName: 'Get URL App Service'      
